name: Publish package

on:
  release:
    types: [created]

jobs:

  build:
    runs-on: ubuntu-latest

    strategy:
        fail-fast: false
        matrix:
            # the Node.js versions to build on
            node-version: [18.x, 20.x]

    steps:
      - uses: actions/checkout@v4

      - name: Use Node.js ${{ matrix.node-version }} 
        uses: actions/setup-node@v3
        with:
            node-version: ${{ matrix.node-version }}

      - name: Install dependencies
        run: npm ci
 #     - run: npm test

  publish-gpr:
    needs: build
    runs-on: ubuntu-latest

    strategy:
        fail-fast: false
        matrix:
            # the Node.js versions to build on
            node-version: [18.x, 20.x]

    permissions:
      packages: write
      contents: read
    steps:
      - uses: actions/checkout@v4

      - name: Use Node.js ${{ matrix.node-version }} 
        uses: actions/setup-node@v3
        with:
            node-version: ${{ matrix.node-version }}
            registry-url: https://npm.pkg.github.com/

      - name: Install dependencies
        run: npm ci

      - name: Publish to registry 
        run: npm publish
        env:
          NODE_AUTH_TOKEN: ${{secrets.GITHUB_TOKEN}}
